export interface BOOK_LIST {
  GENESIS: string;
  EXODUS: string;
  LEVITICUS: string;
  NUMBERS: string;
  DEUTERONOMY: string;
  JOSHUA?: string;
  JUDGES: string;
  RUTH?: string;
  SAMUEL_ONE?: string;
  SAMUEL_TWO?: string;
  KINGS_ONE: string;
  KINGS_TWO: string;
  CHRONICLES_ONE: string;
  CHRONICLES_TWO: string;
  EZRA?: string;
  NEHEMIAH?: string;
  TOBIAS?: string;
  ESTHER?: string;
  JOB: string;
  PSALM: string;
  PROVERBS: string;
  ECCLESIASTES?: string;
  SONG_OF_SOLOMON?: string;
  WISDOM?: string;
  ISAIAH: string;
  JEREMIAH: string;
  LAMENTATIONS?: string;
  BARUCH?: string;
  EZEKIEL: string;
  DANIEL: string;
  HOSEA?: string;
  JOEL?: string;
  AMOS?: string;
  OBADIAH?: string;
  JONAH: string;
  MICAH?: string;
  NAHUM: string;
  HABAKKUK?: string;
  ZEPHANIAH?: string;
  HAGGAI: string;
  ZECHARIAH?: string;
  MALACHI: string;
  MATTHEW: string;
  MARK: string;
  LUKE: string;
  JOHN: string;
  ACTS: string;
  ROMANS: string;
  CORINTHIANS_ONE: string;
  CORINTHIANS_TWO: string;
  GALATIANS: string;
  EPHESIANS: string;
  PHILIPPIANS: string;
  COLOSSIANS: string;
  TIMOTHY_ONE: string;
  THESSALONIANS_ONE: string;
  THESSALONIANS_TWO: string;
  TIMOTHY_TWO?: string;
  TITUS: string;
  PHILEMON?: string;
  HEBREWS: string;
  JAMES: string;
  PETER_ONE: string;
  PETER_TWO: string;
  JOHN_ONE: string;
  JOHN_TWO: string;
  JOHN_THREE?: string;
  JUDE: string;
  REVELATION: string;
  JUDITH?: string;
}

export default class BOOKS {
  //
  static ENGLISH: BOOK_LIST = {
    GENESIS: "GENESIS",
    EXODUS: "EXODUS",
    LEVITICUS: "LEVITICUS",
    NUMBERS: "NUMBERS",
    DEUTERONOMY: "DEUTERONOMY",
    JOSHUA: "JOSHUA",
    JUDGES: "JUDGES",
    RUTH: "RUTH",
    SAMUEL_ONE: "1 SAMUEL",
    SAMUEL_TWO: "2 SAMUEL",
    KINGS_ONE: "1 KINGS",
    KINGS_TWO: "2 KINGS",
    CHRONICLES_ONE: "1 CHRONICLES",
    CHRONICLES_TWO: "2 CHRONICLES",
    EZRA: "EZRA",
    NEHEMIAH: "NEHEMIAH",
    ESTHER: "ESTHER",
    JOB: "JOB",
    PSALM: "PSALM",
    PROVERBS: "PROVERBS",
    ECCLESIASTES: "ECCLESIASTES",
    SONG_OF_SOLOMON: "SONG OF SOLOMON",
    ISAIAH: "ISAIAH",
    JEREMIAH: "JEREMIAH",
    LAMENTATIONS: "LAMENTATIONS",
    EZEKIEL: "EZEKIEL",
    DANIEL: "DANIEL",
    HOSEA: "HOSEA",
    JOEL: "JOEL",
    AMOS: "AMOS",
    OBADIAH: "OBADIAH",
    JONAH: "JONAH",
    MICAH: "MICAH",
    NAHUM: "NAHUM",
    HABAKKUK: "HABAKKUK",
    ZEPHANIAH: "ZEPHANIAH",
    HAGGAI: "HAGGAI",
    ZECHARIAH: "ZECHARIAH",
    MALACHI: "MALACHI",
    MATTHEW: "MATTHEW",
    MARK: "MARK",
    LUKE: "LUKE",
    JOHN: "JOHN",
    ACTS: "ACTS",
    ROMANS: "ROMANS",
    CORINTHIANS_ONE: "1 CORINTHIANS",
    CORINTHIANS_TWO: "2 CORINTHIANS",
    GALATIANS: "GALATIANS",
    EPHESIANS: "EPHESIANS",
    PHILIPPIANS: "PHILIPPIANS",
    COLOSSIANS: "COLOSSIANS",
    THESSALONIANS_ONE: "1 THESSALONIANS",
    THESSALONIANS_TWO: "2 THESSALONIANS",
    TIMOTHY_ONE: "1 TIMOTHY",
    TIMOTHY_TWO: "2 TIMOTHY",
    TITUS: "TITUS",
    PHILEMON: "PHILEMON",
    HEBREWS: "HEBREWS",
    JAMES: "JAMES",
    PETER_ONE: "1 PETER",
    PETER_TWO: "2 PETER",
    JOHN_ONE: "1 JOHN",
    JOHN_TWO: "2 JOHN",
    JOHN_THREE: "3 JOHN",
    JUDE: "JUDE",
    REVELATION: "REVELATION",
  };
  //
  static LATIN: BOOK_LIST = {
    GENESIS: "GENESIS",
    EXODUS: "EXODUS",
    LEVITICUS: "LEVITICUS",
    NUMBERS: "NUMERI",
    DEUTERONOMY: "DEUTERONOMIUM",
    JOSHUA: "JOSUE",
    JUDGES: "JUDICUM",
    RUTH: "RUTH",
    SAMUEL_ONE: "SAMUHEL I",
    SAMUEL_TWO: "SAMUHEL II",
    KINGS_ONE: "REGUM III",
    KINGS_TWO: "REGUM IV",
    CHRONICLES_ONE: "PARALIPOMENON I",
    CHRONICLES_TWO: "PARALIPOMENON I",
    EZRA: "ESDRAE",
    NEHEMIAH: "NEHEMIAE",
    TOBIAS: "TOBIAE",
    JUDITH: "JUDITH",
    ESTHER: "ESTHER",
    JOB: "JOB",
    PSALM: "PSALMI",
    PROVERBS: "PROVERBIA",
    ECCLESIASTES: "ECCLESIASTES",
    SONG_OF_SOLOMON: "CANTICUM CANTICORUM",
    WISDOM: "WISDOM",
    ISAIAH: "ISIAS",
    JEREMIAH: "JEREMIAS",
    LAMENTATIONS: "LAMENTATIONS",
    BARUCH: "BARUCH",
    EZEKIEL: "EZECHIEL",
    DANIEL: "DANIEL",
    HOSEA: "OSEE",
    JOEL: "JOEL",
    AMOS: "AMOS",
    OBADIAH: "ABDIAS",
    JONAH: "JONAS",
    MICAH: "MICHAEA",
    NAHUM: "NAHUM",
    HABAKKUK: "HABACUC",
    ZEPHANIAH: "SOPHONIAS",
    HAGGAI: "AGGAEUS",
    ZECHARIAH: "ZACHARIAS",
    MALACHI: "MALACHIAS",
    MATTHEW: "MATTHAEUM",
    MARK: "SECUNDUM MARCUM",
    LUKE: "SECUNDUM LUCAM",
    JOHN: "SECUNDUM IOANNEM",
    ACTS: "ACTUS APOSTOLOTUM",
    ROMANS: "AD ROMANOS",
    CORINTHIANS_ONE: "AD CORINTHIOS I",
    CORINTHIANS_TWO: "AD CORINTHIOS II",
    GALATIANS: "AD GALATAS",
    EPHESIANS: "AD EPHESIOS",
    PHILIPPIANS: "AD PHILLIPPENSES",
    COLOSSIANS: "AD COLOSSENSES",
    THESSALONIANS_ONE: "AD THESSALONICENSES I",
    THESSALONIANS_TWO: "AD THESSALONICENSES II",
    TIMOTHY_ONE: "AD TIMOTHEUM I",
    TIMOTHY_TWO: "AD TIMOTHEUM II",
    TITUS: "AD TITUM",
    PHILEMON: "AD PHILEMONEM",
    HEBREWS: "AD HEBRAEOS",
    JAMES: "EPISTULA IACOBI",
    PETER_ONE: "EPISTULA PETRI I",
    PETER_TWO: "EPISTULA PETRI II",
    JOHN_ONE: "EPISTULA IOANNIS I",
    JOHN_TWO: "EPISTULA IOANNIS II",
    JOHN_THREE: "EPISTULA IOANNIS II",
    JUDE: "EPISTULA IUDAE",
    REVELATION: "APOLOALYPSIS IOANNIS",
  };
}
